variable "enabled" {
  type        = bool
  description = "Internal template switch. The dedicated Terraform-only stack sets this to true."
}

variable "context" {
  description = "Shared OCI identifiers and safe test-run context."
  type = object({
    tenancy_ocid         = string
    user_ocid            = string
    compartment_ocid     = string
    region               = string
    resource_id          = string
    resource_name_prefix = string
    tester_source_cidr   = string
    vcn_ocid             = string
    public_subnet_ocid   = string
    private_subnet_ocid  = string
  })
}

variable "generated_values" {
  type        = map(string)
  description = "Passwords and values generated by the shared metadata module."
  sensitive   = true
}

variable "settings" {
  type        = map(string)
  description = "Project-specific non-secret values from terraform.tfvars."
  default     = {}
}

variable "sensitive_settings" {
  type        = map(string)
  description = "Project-specific sensitive values from terraform.tfvars. Prefer generated_values when possible."
  default     = {}
  sensitive   = true
}

# Add project resources in this folder. Every resource must use count or
# for_each with var.enabled. Restrict direct access to
# var.context.tester_source_cidr when access is required.
#
# After adding resources, replace these empty values:
# - summary: safe labels or OCIDs that may be printed after a successful test.
# - test_context: only the values required by provisioning-tests/*.ps1.
#
# Example shape:
# locals {
#   resource_summary = var.enabled ? ["Autonomous Database: ${oci_database_autonomous_database.example[0].display_name}"] : []
#   resource_test_context = var.enabled ? {
#     database_ocid = oci_database_autonomous_database.example[0].id
#     username      = "LLUSER"
#     password      = var.generated_values["resource_password"]
#   } : {}
# }

locals {
  resource_summary      = []
  resource_test_context = {}
}

output "summary" {
  description = "Safe resource details printed in the final test summary."
  value       = local.resource_summary
}

output "test_context" {
  description = "Sensitive machine-readable context passed only to provisioning tests."
  value       = local.resource_test_context
  sensitive   = true
}
